spring:
  application:
    name: coop-erp-backend
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5434/coop_erp}
    username: ${DB_USER:postgres}
    password: ${DB_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver
  flyway:
    enabled: false
knoweb:
  migration:
    url: ${DB_URL:jdbc:postgresql://localhost:5434/coop_erp}
    user: ${MIGRATION_USER:postgres}
    password: ${MIGRATION_PASSWORD:postgres}
