== CoopErpApplication
plantuml::components.puml[,,format=svg]

== Config
plantuml::module-config.puml[,,format=svg]
include::module-config.adoc[]

== Engine
plantuml::module-engine.puml[,,format=svg]
include::module-engine.adoc[]

== Platform Kernel
plantuml::module-kernel.puml[,,format=svg]
include::module-kernel.adoc[]

== Hello (template module)
plantuml::module-hello.puml[,,format=svg]
include::module-hello.adoc[]

== M1 Party, Tenancy & Security
plantuml::module-m1party.puml[,,format=svg]
include::module-m1party.adoc[]

== M2 Catalogue & Batch
plantuml::module-m2catalogue.puml[,,format=svg]
include::module-m2catalogue.adoc[]

== M6 Point of Sale
plantuml::module-m6pos.puml[,,format=svg]
include::module-m6pos.adoc[]

== M9 Integration
plantuml::module-m9integration.puml[,,format=svg]
include::module-m9integration.adoc[]

== M3 Pricing & Rules
plantuml::module-m3pricing.puml[,,format=svg]
include::module-m3pricing.adoc[]

== M7 Customers & Payment Recording
plantuml::module-m7customers.puml[,,format=svg]
include::module-m7customers.adoc[]

== M8 Reporting Pipeline
plantuml::module-m8reporting.puml[,,format=svg]
include::module-m8reporting.adoc[]

== M5 Inventory, Costing, Repack & Loss
plantuml::module-m5inventory.puml[,,format=svg]
include::module-m5inventory.adoc[]

== M4 Trading Documents
plantuml::module-m4trading.puml[,,format=svg]
include::module-m4trading.adoc[]

== Demo data
plantuml::module-demo.puml[,,format=svg]
include::module-demo.adoc[]

